/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa1_Presentacion;

import Capa2_Aplicacion.ServGestionarPeriodo;
import Capa3_Dominio.Periodo;
import Capa5_Excepcion.Mensaje;
import Capa6_Globales.IngresoDni;
import Capa6_Globales.TerminarAplicacion;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author JOSEPOLANCO
 */
public class MenuPrincipal extends javax.swing.JFrame {

     private List<Periodo> listaPeriodo;
     Periodo periodo;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.getContentPane().setBackground(new Color(153,153,153));
        setSize(710,370);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Sistema de Nomina");
        EventoTecla();
        setMnemonic();
    }
    
    void EventoTecla(){
        TerminarAplicacion atjCerrar = new TerminarAplicacion(this);
    }
    public void BuscarPeriodos(){    
       try{
           ServGestionarPeriodo gestionarPeriodo = new ServGestionarPeriodo();
           listaPeriodo = gestionarPeriodo.BuscarPeriodos();    
       }catch (Exception e) {  
           Mensaje.mostrarError(null, "Error de Registro");            
       }
       if (listaPeriodo == null){
           Mensaje.mostrarAfirmacion(null, "Sin periodos registrados");
       }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        menEmpleado = new javax.swing.JMenu();
        menRegistraEmpleado = new javax.swing.JMenuItem();
        menContrato = new javax.swing.JMenu();
        menRegistraContrato = new javax.swing.JMenuItem();
        menAfp = new javax.swing.JMenu();
        menRegistraAfp = new javax.swing.JMenuItem();
        menPeriodo = new javax.swing.JMenu();
        menRegistraPeriodo = new javax.swing.JMenuItem();
        menProcesarPagos = new javax.swing.JMenu();
        menProcesar = new javax.swing.JMenuItem();
        menAyuda = new javax.swing.JMenu();
        menSesion = new javax.swing.JMenu();
        menCerrarSesion = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menEmpleado.setText("Gestionar Empleado");

        menRegistraEmpleado.setText("Registrar Empleado");
        menRegistraEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRegistraEmpleadoActionPerformed(evt);
            }
        });
        menEmpleado.add(menRegistraEmpleado);

        jMenuBar3.add(menEmpleado);

        menContrato.setText("Gestionar Contrato");

        menRegistraContrato.setText("Registrar Contrato");
        menRegistraContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRegistraContratoActionPerformed(evt);
            }
        });
        menContrato.add(menRegistraContrato);

        jMenuBar3.add(menContrato);

        menAfp.setText("Gestionar Afp");

        menRegistraAfp.setText("Registrar Afp");
        menRegistraAfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRegistraAfpActionPerformed(evt);
            }
        });
        menAfp.add(menRegistraAfp);

        jMenuBar3.add(menAfp);

        menPeriodo.setText("GestionarPeriodo");

        menRegistraPeriodo.setText("Registrar Periodo");
        menRegistraPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRegistraPeriodoActionPerformed(evt);
            }
        });
        menPeriodo.add(menRegistraPeriodo);

        jMenuBar3.add(menPeriodo);

        menProcesarPagos.setText("Procesar Pagos");

        menProcesar.setText("Procesar");
        menProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menProcesarActionPerformed(evt);
            }
        });
        menProcesarPagos.add(menProcesar);

        jMenuBar3.add(menProcesarPagos);

        menAyuda.setText("Ayuda");
        jMenuBar3.add(menAyuda);

        menSesion.setText("Sesion");

        menCerrarSesion.setText("Cerrar Sesion");
        menCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCerrarSesionActionPerformed(evt);
            }
        });
        menSesion.add(menCerrarSesion);

        jMenuBar3.add(menSesion);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menRegistraEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRegistraEmpleadoActionPerformed
        // TODO add your handling code here:
        IngresoDni ingresoDni = new IngresoDni(null, true);
        if(ingresoDni.retornaDni().compareTo("")!=0 && ingresoDni.retornaDni().length() == 8){ 
            DlgEmpleado DE = new DlgEmpleado(this, true);
            DE.ObtenerDni(ingresoDni.retornaDni());
            DE.setVisible(true);    
        }
    }//GEN-LAST:event_menRegistraEmpleadoActionPerformed

    private void menRegistraContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRegistraContratoActionPerformed
        // TODO add your handling code here:
        IngresoDni ingresoDni = new IngresoDni(null, true);
        if(ingresoDni.retornaDni().compareTo("")!=0 && ingresoDni.retornaDni().length() == 8){ 
            DlgGestionarContrato DC = new DlgGestionarContrato(this, true);
            DC.ObtenerDni(ingresoDni.retornaDni());
            DC.setVisible(true);     
        }

        
    }//GEN-LAST:event_menRegistraContratoActionPerformed

    private void menRegistraAfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRegistraAfpActionPerformed
        // TODO add your handling code here:
        DlgAfp DA = new DlgAfp(this, true);
        DA.setVisible(true); 
    }//GEN-LAST:event_menRegistraAfpActionPerformed

    private void menCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }//GEN-LAST:event_menCerrarSesionActionPerformed

    private void menRegistraPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRegistraPeriodoActionPerformed
            DlgPeriodo DP = new DlgPeriodo(this, true);
            DP.setVisible(true);
    }//GEN-LAST:event_menRegistraPeriodoActionPerformed

    private void menProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menProcesarActionPerformed
        // TODO add your handling code here:
         BuscarPeriodos();
       if (listaPeriodo != null) {
           for (Periodo objetoPeriodo : listaPeriodo) {
               if (objetoPeriodo.verificarPeriodoVigente()) {
                   periodo = objetoPeriodo;                  
                   break;
               }
           }
           if (periodo != null) {
               DlgProcesarPago DPP = new DlgProcesarPago(this, true);
               DPP.setVisible(true);
           }else{
               JOptionPane.showMessageDialog(this, "No se puede procesar porque no existe periodo de pago activo");
           }
       }
    }//GEN-LAST:event_menProcesarActionPerformed

    void setMnemonic(){
        menEmpleado.setMnemonic(KeyEvent.VK_E);
        menRegistraEmpleado.setMnemonic(KeyEvent.VK_R);
        KeyStroke ksEmpleado = KeyStroke.getKeyStroke("alt R");
        menRegistraEmpleado.setAccelerator(ksEmpleado);
        
        menContrato.setMnemonic(KeyEvent.VK_C);
        menRegistraContrato.setMnemonic(KeyEvent.VK_R);
        KeyStroke ksContrato = KeyStroke.getKeyStroke("alt R");
        menRegistraContrato.setAccelerator(ksContrato);
        
        menAfp.setMnemonic(KeyEvent.VK_A);
        menRegistraAfp.setMnemonic(KeyEvent.VK_R);
        KeyStroke ksAfp = KeyStroke.getKeyStroke("alt R");
        menRegistraAfp.setAccelerator(ksAfp);
        
        menPeriodo.setMnemonic(KeyEvent.VK_P);
        menRegistraPeriodo.setMnemonic(KeyEvent.VK_R);
        KeyStroke ksPeriodo = KeyStroke.getKeyStroke("alt R");
        menRegistraPeriodo.setAccelerator(ksPeriodo);
        
        menProcesarPagos.setMnemonic(KeyEvent.VK_R);
        menProcesar.setMnemonic(KeyEvent.VK_P);
        KeyStroke ksProcesar = KeyStroke.getKeyStroke("alt P");
        menProcesar.setAccelerator(ksProcesar);
        
        menAyuda.setMnemonic(KeyEvent.VK_Y);
        
        menSesion.setMnemonic(KeyEvent.VK_S);
        menCerrarSesion.setMnemonic(KeyEvent.VK_C);
        KeyStroke ksSesion = KeyStroke.getKeyStroke("alt C");
        menCerrarSesion.setAccelerator(ksSesion);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu menAfp;
    private javax.swing.JMenu menAyuda;
    private javax.swing.JMenuItem menCerrarSesion;
    private javax.swing.JMenu menContrato;
    private javax.swing.JMenu menEmpleado;
    private javax.swing.JMenu menPeriodo;
    private javax.swing.JMenuItem menProcesar;
    private javax.swing.JMenu menProcesarPagos;
    private javax.swing.JMenuItem menRegistraAfp;
    private javax.swing.JMenuItem menRegistraContrato;
    private javax.swing.JMenuItem menRegistraEmpleado;
    private javax.swing.JMenuItem menRegistraPeriodo;
    private javax.swing.JMenu menSesion;
    // End of variables declaration//GEN-END:variables
}
