/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa1_Presentacion;

import java.awt.Color;
import javax.swing.SwingUtilities;

/**
 *
 * @author JOSEPOLANCO
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this .getContentPane().setBackground(new Color(255,255,255));
        setSize(710,370);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Sistema de Nomina");      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        menEmpleado = new javax.swing.JMenu();
        menRegistraEmpleado = new javax.swing.JMenuItem();
        menContrato = new javax.swing.JMenu();
        menRegistraContrato = new javax.swing.JMenuItem();
        menAfp = new javax.swing.JMenu();
        menRegistrarAfp = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuperiodo = new javax.swing.JMenuItem();
        menAyuda = new javax.swing.JMenu();
        menSesion = new javax.swing.JMenu();
        menCerrarSesion = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menEmpleado.setText("Gestionar Empleado");

        menRegistraEmpleado.setText("Registra Empleado");
        menRegistraEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRegistraEmpleadoActionPerformed(evt);
            }
        });
        menEmpleado.add(menRegistraEmpleado);

        jMenuBar3.add(menEmpleado);

        menContrato.setText("Gestionar Contrato");

        menRegistraContrato.setText("Registrar Contrato");
        menRegistraContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRegistraContratoActionPerformed(evt);
            }
        });
        menContrato.add(menRegistraContrato);

        jMenuBar3.add(menContrato);

        menAfp.setText("Gestionar Afp");

        menRegistrarAfp.setText("Registrar Afp");
        menRegistrarAfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRegistrarAfpActionPerformed(evt);
            }
        });
        menAfp.add(menRegistrarAfp);

        jMenuBar3.add(menAfp);

        jMenu3.setText("GestionarPeriodo");

        menuperiodo.setText("RegistrarPeriodo");
        menuperiodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuperiodoActionPerformed(evt);
            }
        });
        jMenu3.add(menuperiodo);

        jMenuBar3.add(jMenu3);

        menAyuda.setText("Ayuda");
        jMenuBar3.add(menAyuda);

        menSesion.setText("Sesion");

        menCerrarSesion.setText("Cerrar Sesion");
        menCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCerrarSesionActionPerformed(evt);
            }
        });
        menSesion.add(menCerrarSesion);

        jMenuBar3.add(menSesion);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menRegistraEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRegistraEmpleadoActionPerformed
        // TODO add your handling code here:
        DlgEmpleado DE = new DlgEmpleado(this, true);
        DE.setVisible(true); 
    }//GEN-LAST:event_menRegistraEmpleadoActionPerformed

    private void menRegistraContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRegistraContratoActionPerformed
        // TODO add your handling code here:
        DlgGestionarContrato DC = new DlgGestionarContrato(this, true);
        DC.setVisible(true); 
    }//GEN-LAST:event_menRegistraContratoActionPerformed

    private void menRegistrarAfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRegistrarAfpActionPerformed
        // TODO add your handling code here:
        DlgAfp DA = new DlgAfp(this, true);
        DA.setVisible(true); 
    }//GEN-LAST:event_menRegistrarAfpActionPerformed

    private void menCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }//GEN-LAST:event_menCerrarSesionActionPerformed

    private void menuperiodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuperiodoActionPerformed
            DlgPeriodo DP = new DlgPeriodo(this, true);
            DP.setVisible(true);
    }//GEN-LAST:event_menuperiodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu menAfp;
    private javax.swing.JMenu menAyuda;
    private javax.swing.JMenuItem menCerrarSesion;
    private javax.swing.JMenu menContrato;
    private javax.swing.JMenu menEmpleado;
    private javax.swing.JMenuItem menRegistraContrato;
    private javax.swing.JMenuItem menRegistraEmpleado;
    private javax.swing.JMenuItem menRegistrarAfp;
    private javax.swing.JMenu menSesion;
    private javax.swing.JMenuItem menuperiodo;
    // End of variables declaration//GEN-END:variables
}
