/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa1_Presentacion;

import Capa2_Aplicacion.ServGestionarAfp;
import Capa2_Aplicacion.ServGestionarContrato;
import Capa2_Aplicacion.ServGestionarEmpleado;
import Capa3_Dominio.Afp;
import Capa3_Dominio.Contrato;
import Capa3_Dominio.Empleado;
import Capa5_Excepcion.Mensaje;
import Capa6_Globales.Objeto;
import Capa6_Globales.VGlobales;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author lucab
 */
public class DlgContrato extends javax.swing.JDialog {

    /**
     * Creates new form DlgContrato
     */
    private Contrato contrato;
    private Empleado empleado;
    private Afp afp;
    private List<Afp> listaAfps;
    private DefaultComboBoxModel modeloAfp;
    private Objeto datosAfp;
    
    public DlgContrato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this .getContentPane().setBackground(new Color(255,255,255));
        setLocationRelativeTo(null);
        setResizable(false); 
        setTitle("Contrato");
        EstadoDefault();
        LlenarCombo();
    }

    
    void EstadoDefault(){
        
    }

    public void VerificarContrato(String dni){
        
    }      
    
    public void MostrarDatos(Contrato contrato){
            
    }
    
    public void VerificarEmpleado(String dni){      
        
        try{
            ServGestionarEmpleado gestionarEmpleado = new ServGestionarEmpleado();
            empleado = gestionarEmpleado.VerificarEmpleado(dni);  
        }catch (Exception e) {   
            Mensaje.mostrarError(this, "Error de Registro Empleado");            
        } 
        if (empleado == null){
            Mensaje.mostrarAfirmacion(this, "No exite empleado");
        }
    }
    
    public void VerificarAfp(int idAfp){             
        try{
            ServGestionarAfp gestionarAfp = new ServGestionarAfp();
            afp = gestionarAfp.VerificarAfp(idAfp);  
        }catch (Exception e) {   
            Mensaje.mostrarError(this, "Error de Registro Afp");            
        } 
        if (afp == null){
            Mensaje.mostrarAfirmacion(this, "No exite Afp");
        }
    }
    
    public void ConsultaAfp(){ 
        try{
            ServGestionarAfp gestionarAfp = new ServGestionarAfp();
            listaAfps = gestionarAfp.BuscarAfps();               
        } catch (Exception e) {
            Mensaje.mostrarError(this, e.getMessage());   
        }
    }

    private void LlenarCombo(){  
        ConsultaAfp();
        cboAfp.removeAllItems();
        if(listaAfps != null){         
            modeloAfp = new DefaultComboBoxModel();
            cboAfp.setModel(modeloAfp);           
            modeloAfp.addElement(new Objeto("<Seleccionar>", 0));
            for(Afp afp : listaAfps){
                datosAfp = new Objeto(afp.getNombre(), afp.getIdafp());
                modeloAfp.addElement(datosAfp);
            }
        }else
                Mensaje.mostrarAdvertencia(this, "Lista vacia");   
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jdcFechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jdcFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboAfp = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        chkAsignacion = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txtHorasSemana = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtValorHora = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Fecha Inicio:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        getContentPane().add(jdcFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 160, -1));

        jLabel2.setText("Fecha Fin:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        getContentPane().add(jdcFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 160, -1));

        jLabel3.setText("Cargo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
        getContentPane().add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 210, -1));

        jLabel4.setText("Afp Asociada:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        cboAfp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        getContentPane().add(cboAfp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 140, -1));

        jLabel5.setText("Asignacion Familiar:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        chkAsignacion.setText("Si");
        getContentPane().add(chkAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel6.setText("Horas/Semana:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        getContentPane().add(txtHorasSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 140, -1));

        jLabel7.setText("Valor/Hora:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        getContentPane().add(txtValorHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 140, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 100, -1));

        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String Cargo, AfpAsignada, Condicion = "ACTIVO";
        int HorasSemana, idEmpleado;
        Boolean Estatus;
        double ValorHora;
        
        if(txtCargo.getText().compareTo("")!=0 && txtHorasSemana.getText().compareTo("")!=0 && txtValorHora.getText().compareTo("")!=0)
        {
            long date;
            Date fecha;       
            date = 0;
            fecha = jdcFechaInicio.getDate();
            date = fecha.getTime();
            java.sql.Date FechaInicio = new java.sql.Date(date); 
            date = 0; 
            fecha = jdcFechaFin.getDate(); 
            date = fecha.getTime();
            java.sql.Date FechaFin = new java.sql.Date(date); 
            Cargo = (txtCargo.getText());                  
            AfpAsignada = (String.valueOf(cboAfp.getSelectedItem()));  
            
            if(chkAsignacion.isSelected()){
                Estatus = true;
            }else
                Estatus = false;
            HorasSemana = Integer.valueOf(txtHorasSemana.getText()); 
            ValorHora = Double.valueOf(txtValorHora.getText()); 
 
            String Dni = VGlobales.globalDNI;
            if(Dni.compareTo("")!=0){
                VerificarEmpleado(Dni);
            }
            
            int indice = cboAfp.getSelectedIndex();
            Objeto ObjAfp = (Objeto)modeloAfp.getElementAt(indice);
            int idAfp =ObjAfp.getCodigo();            
            if(idAfp >=0){
                VerificarAfp(idAfp);
            }
            try {            
                contrato = new Contrato(empleado, afp, FechaInicio, FechaFin, Cargo, Estatus, HorasSemana, ValorHora, Condicion);                    
                ServGestionarContrato gestionarContrato = new ServGestionarContrato();
                gestionarContrato.IngresarContrato(contrato);              
                JOptionPane.showMessageDialog(null,"Dato registrado");
                btnRegistrar.setText("Actualizar");
                btnCancelar.setText("Finalizar");  
                //VerificarContrato(Dni);
                //MostrarDatos(contrato);
            } catch (Exception e) {
                Mensaje.mostrarError(this, "Error de Ingreso");
            }
            } else
                JOptionPane.showMessageDialog(null,"faltan llenar datos");
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgContrato dialog = new DlgContrato(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboAfp;
    private javax.swing.JCheckBox chkAsignacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.toedter.calendar.JDateChooser jdcFechaFin;
    private com.toedter.calendar.JDateChooser jdcFechaInicio;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtHorasSemana;
    private javax.swing.JTextField txtValorHora;
    // End of variables declaration//GEN-END:variables
}
