/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa1_Presentacion;

import java.awt.Color;

/**
 *
 * @author JOSEPOLANCO
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this .getContentPane().setBackground(new Color(255,255,255));
        setSize(710,370);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Sistema de Nomina");      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        menEmpleado = new javax.swing.JMenu();
        menRegistraEmpleado = new javax.swing.JMenuItem();
        menContrato = new javax.swing.JMenu();
        menRegistraContrato = new javax.swing.JMenuItem();
        menAyuda = new javax.swing.JMenu();
        menucuenta = new javax.swing.JMenu();
        menucerrarsesion = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar4.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("jMenu7");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menEmpleado.setText("Gestionar Empleado");

        menRegistraEmpleado.setText("Registra Empleado");
        menRegistraEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRegistraEmpleadoActionPerformed(evt);
            }
        });
        menEmpleado.add(menRegistraEmpleado);

        jMenuBar3.add(menEmpleado);

        menContrato.setText("Gestionar Contrato");

        menRegistraContrato.setText("Registrar Contrato");
        menRegistraContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRegistraContratoActionPerformed(evt);
            }
        });
        menContrato.add(menRegistraContrato);

        jMenuBar3.add(menContrato);

        menAyuda.setText("Ayuda");
        jMenuBar3.add(menAyuda);

        menucuenta.setText("Cuenta");

        menucerrarsesion.setText("CerrarSesion");
        menucerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucerrarsesionActionPerformed(evt);
            }
        });
        menucuenta.add(menucerrarsesion);

        jMenuBar3.add(menucuenta);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menRegistraEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRegistraEmpleadoActionPerformed
        // TODO add your handling code here:
        DlgEmpleado DE = new DlgEmpleado(this, true);
        DE.setVisible(true); 
    }//GEN-LAST:event_menRegistraEmpleadoActionPerformed

    private void menRegistraContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRegistraContratoActionPerformed
        // TODO add your handling code here:
        DlgGestionarContrato DC = new DlgGestionarContrato(this, true);
        DC.setVisible(true); 
    }//GEN-LAST:event_menRegistraContratoActionPerformed

    private void menucerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucerrarsesionActionPerformed
        Login L = new Login();
        L.setVisible(true);
    }//GEN-LAST:event_menucerrarsesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menAyuda;
    private javax.swing.JMenu menContrato;
    private javax.swing.JMenu menEmpleado;
    private javax.swing.JMenuItem menRegistraContrato;
    private javax.swing.JMenuItem menRegistraEmpleado;
    private javax.swing.JMenuItem menucerrarsesion;
    private javax.swing.JMenu menucuenta;
    // End of variables declaration//GEN-END:variables
}
