/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa1_Presentacion;

import Capa2_Aplicacion.ServGestionarContrato;
import Capa2_Aplicacion.ServGestionarPeriodo;
import Capa3_Dominio.Contrato;
import Capa3_Dominio.Periodo;
import Capa5_Excepcion.Mensaje;
import Capa1_Presentacion.Utilidades.TerminarAplicacion;
import Capa6_Globales.VariablesGlobales;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.Timer;

/**
 *
 * @author JOSEPOLANCO
 */
public class MenuPrincipal extends JFrame {

    /**
     * Creates new form MenuPrincipal
     */

    private transient Periodo periodo;
    private transient ServGestionarPeriodo gestionarPeriodo;
    transient TerminarAplicacion atjCerrar;
    private final java.util.Date fechaActual  = new java.util.Date();
    private transient ServGestionarContrato gestionarContrato;
    private transient List<Contrato> listaContrato;
    
    public MenuPrincipal() {
        initComponents();
        setLayout(null);
        getContentPane().setBackground(new Color(153,153,153));
        setSize(720,350);
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/Capa1_Presentacion/Imagen/iconoNomina.png")).getImage());        
        setTitle("Sistema de Nomina");
        menUltimaSesion.setText("Ultimo inicio a las " + String.format("%TT", new java.util.Date()));
        estadoDefault();
    } 
    
    public void estadoDefault(){
        eventoTecla();
        setMnemonic();        
        relojDigital();
        actualizarEstadoContratos();
    }
    
    void eventoTecla(){
        atjCerrar = new TerminarAplicacion(this);
    }

    public void buscarContratosActivos(){
        try{
            gestionarContrato = new ServGestionarContrato();
            listaContrato = gestionarContrato.buscarContratosActivos();     
        }catch (Exception e) {   
            Mensaje.mostrarError(null, Mensaje.ERROR_SERVICIO + "BuscarContratosActivos()");            
        }
    }
    
    public void actualizarEstadoContratos(){
        Timer timerActualizaEstado = new Timer (10000, (ActionEvent e) -> {
            lblActualizando.setText("");
            buscarContratosActivos();
            if(!listaContrato.isEmpty()){
                for(Contrato objetoContrato : listaContrato){
                    if(objetoContrato.getFechafincontrato().getTime() < fechaActual.getTime()){
                        lblActualizando.setText("Actualizando...");
                        try {
                            gestionarContrato = new ServGestionarContrato();
                            gestionarContrato.actualizarEstadoContrato(objetoContrato);
                        } catch (Exception ex) {
                            Mensaje.mostrarError(null, Mensaje.ERROR_SERVICIO + "actualizarEstadoContratos()");  
                        }
                    }
                }
            }
        });    
        timerActualizaEstado.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        lblNominaSoft = new javax.swing.JLabel();
        lblHoraActual = new javax.swing.JLabel();
        lblFechaActual = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        lblHoraActual1 = new javax.swing.JLabel();
        lblFechaActual1 = new javax.swing.JLabel();
        lblActualizando = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        menEmpleado = new javax.swing.JMenu();
        menRegistraEmpleado = new javax.swing.JMenuItem();
        menContrato = new javax.swing.JMenu();
        menRegistraContrato = new javax.swing.JMenuItem();
        menAfp = new javax.swing.JMenu();
        menRegistraAfp = new javax.swing.JMenuItem();
        menPeriodo = new javax.swing.JMenu();
        menRegistraPeriodo = new javax.swing.JMenuItem();
        menProcesarPagos = new javax.swing.JMenu();
        menProcesar = new javax.swing.JMenuItem();
        menAyuda = new javax.swing.JMenu();
        menSesion = new javax.swing.JMenu();
        menCerrarSesion = new javax.swing.JMenuItem();
        menUltimaSesion = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNominaSoft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capa1_Presentacion/Imagen/fondoNomina.png"))); // NOI18N
        getContentPane().add(lblNominaSoft, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 300));

        lblHoraActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHoraActual.setForeground(new java.awt.Color(255, 255, 255));
        lblHoraActual.setText("Hora");
        getContentPane().add(lblHoraActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 220, 50));

        lblFechaActual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFechaActual.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaActual.setText("Fecha");
        getContentPane().add(lblFechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 240, -1));

        lblBienvenido.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenido.setText("Bienvenido");
        getContentPane().add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 40));

        lblHoraActual1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHoraActual1.setForeground(new java.awt.Color(255, 255, 255));
        lblHoraActual1.setText("Son las ");
        getContentPane().add(lblHoraActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 50));

        lblFechaActual1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFechaActual1.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaActual1.setText("del ");
        getContentPane().add(lblFechaActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 30, -1));
        getContentPane().add(lblActualizando, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 274, 110, 20));

        menEmpleado.setText("Gestionar Empleado");

        menRegistraEmpleado.setText("Registrar Empleado");
        menRegistraEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRegistraEmpleadoActionPerformed(evt);
            }
        });
        menEmpleado.add(menRegistraEmpleado);

        jMenuBar3.add(menEmpleado);

        menContrato.setText("Gestionar Contrato");

        menRegistraContrato.setText("Registrar Contrato");
        menRegistraContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRegistraContratoActionPerformed(evt);
            }
        });
        menContrato.add(menRegistraContrato);

        jMenuBar3.add(menContrato);

        menAfp.setText("Gestionar Afp");

        menRegistraAfp.setText("Registrar Afp");
        menRegistraAfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRegistraAfpActionPerformed(evt);
            }
        });
        menAfp.add(menRegistraAfp);

        jMenuBar3.add(menAfp);

        menPeriodo.setText("GestionarPeriodo");

        menRegistraPeriodo.setText("Registrar Periodo");
        menRegistraPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRegistraPeriodoActionPerformed(evt);
            }
        });
        menPeriodo.add(menRegistraPeriodo);

        jMenuBar3.add(menPeriodo);

        menProcesarPagos.setText("Procesar Pagos");

        menProcesar.setText("Procesar");
        menProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menProcesarActionPerformed(evt);
            }
        });
        menProcesarPagos.add(menProcesar);

        jMenuBar3.add(menProcesarPagos);

        menAyuda.setText("Ayuda");
        jMenuBar3.add(menAyuda);

        menSesion.setText("Sesion");

        menCerrarSesion.setText("Cerrar Sesion");
        menCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCerrarSesionActionPerformed(evt);
            }
        });
        menSesion.add(menCerrarSesion);
        menSesion.add(menUltimaSesion);

        jMenuBar3.add(menSesion);

        setJMenuBar(jMenuBar3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menRegistraEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRegistraEmpleadoActionPerformed
        // TODO add your handling code here:
            DlgVerificarEmpleado DVE = new DlgVerificarEmpleado(this, true);
            DVE.obtenerEstado(true);
            DVE.setVisible(true);  

    }//GEN-LAST:event_menRegistraEmpleadoActionPerformed

    private void menRegistraContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRegistraContratoActionPerformed
        // TODO add your handling code here:
            DlgVerificarEmpleado DVE = new DlgVerificarEmpleado(this, true);
            DVE.obtenerEstado(false);
            DVE.setVisible(true);  

    }//GEN-LAST:event_menRegistraContratoActionPerformed

    private void menRegistraAfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRegistraAfpActionPerformed
        // TODO add your handling code here:
        DlgAfp DA = new DlgAfp(this, true);
        DA.setVisible(true);
    }//GEN-LAST:event_menRegistraAfpActionPerformed

    private void menCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }//GEN-LAST:event_menCerrarSesionActionPerformed

    private void menRegistraPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRegistraPeriodoActionPerformed
            DlgPeriodo DP = new DlgPeriodo(this, true);
            DP.setVisible(true);
    }//GEN-LAST:event_menRegistraPeriodoActionPerformed

    private void menProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menProcesarActionPerformed
        // TODO add your handling code here:
        try {
            gestionarPeriodo = new ServGestionarPeriodo();
            periodo = gestionarPeriodo.verificarPeriodoVigente();
        } catch (Exception e) {
           Mensaje.mostrarError(null, Mensaje.ERROR_SERVICIO);            
        }
        if (periodo != null) {
            DlgProcesarPago DPP = new DlgProcesarPago(this, true);
            DPP.setVisible(true);
        }

    }//GEN-LAST:event_menProcesarActionPerformed

    void setMnemonic(){
        menEmpleado.setMnemonic(KeyEvent.VK_E);
        menRegistraEmpleado.setMnemonic(KeyEvent.VK_R);
        KeyStroke ksEmpleado = KeyStroke.getKeyStroke(VariablesGlobales.MNEMONIC_REGISTRAR);
        menRegistraEmpleado.setAccelerator(ksEmpleado);
        
        menContrato.setMnemonic(KeyEvent.VK_C);
        menRegistraContrato.setMnemonic(KeyEvent.VK_R);
        KeyStroke ksContrato = KeyStroke.getKeyStroke(VariablesGlobales.MNEMONIC_REGISTRAR);
        menRegistraContrato.setAccelerator(ksContrato);
        
        menAfp.setMnemonic(KeyEvent.VK_A);
        menRegistraAfp.setMnemonic(KeyEvent.VK_R);
        KeyStroke ksAfp = KeyStroke.getKeyStroke(VariablesGlobales.MNEMONIC_REGISTRAR);
        menRegistraAfp.setAccelerator(ksAfp);
        
        menPeriodo.setMnemonic(KeyEvent.VK_P);
        menRegistraPeriodo.setMnemonic(KeyEvent.VK_R);
        KeyStroke ksPeriodo = KeyStroke.getKeyStroke(VariablesGlobales.MNEMONIC_REGISTRAR);
        menRegistraPeriodo.setAccelerator(ksPeriodo);
        
        menProcesarPagos.setMnemonic(KeyEvent.VK_R);
        menProcesar.setMnemonic(KeyEvent.VK_P);
        KeyStroke ksProcesar = KeyStroke.getKeyStroke("alt P");
        menProcesar.setAccelerator(ksProcesar);
        
        menAyuda.setMnemonic(KeyEvent.VK_Y);
        
        menSesion.setMnemonic(KeyEvent.VK_S);
        menCerrarSesion.setMnemonic(KeyEvent.VK_C);
        KeyStroke ksSesion = KeyStroke.getKeyStroke("alt C");
        menCerrarSesion.setAccelerator(ksSesion);
    }
    
    public void relojDigital(){
        Timer timerHoraFecha = new Timer (1000, (ActionEvent e) -> {
            lblHoraActual.setText(mostrarHora());
            lblFechaActual.setText(mostrarFecha());
        });
        Timer timerTexto = new Timer (10000, (ActionEvent e) -> {
            if(lblBienvenido.getText().equalsIgnoreCase("Bienvenido")){
                if(fechaActual.getHours() >= 6 && fechaActual.getHours() <= 12){
                    lblBienvenido.setText("Buen Día");
                }else if(fechaActual.getHours() >= 13 && fechaActual.getHours() <= 18){
                    lblBienvenido.setText("Buena Tarde");
                }else if(fechaActual.getHours() >= 19 && fechaActual.getHours() <= 23){
                    lblBienvenido.setText("Buena Noche");
                }else if(fechaActual.getHours() >= 0 && fechaActual.getHours() <= 5){
                    lblBienvenido.setText("Buen Trasnoche");
                }
            }else lblBienvenido.setText("Bienvenido");
        });
        timerHoraFecha.start();
        timerTexto.start();
    }
    
    public String mostrarHora(){
        String hora = String.format("%TT", new java.util.Date());
        return hora;
    } 
    
    public String mostrarFecha(){
        SimpleDateFormat formatoFecha = new SimpleDateFormat("EEEE d 'de' MMMM 'de' yyyy",
        new Locale("ES", "PE")); 
        String fecha = formatoFecha.format(fechaActual);
        return fecha;
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JLabel lblActualizando;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JLabel lblFechaActual1;
    private javax.swing.JLabel lblHoraActual;
    private javax.swing.JLabel lblHoraActual1;
    private javax.swing.JLabel lblNominaSoft;
    private javax.swing.JMenu menAfp;
    private javax.swing.JMenu menAyuda;
    private javax.swing.JMenuItem menCerrarSesion;
    private javax.swing.JMenu menContrato;
    private javax.swing.JMenu menEmpleado;
    private javax.swing.JMenu menPeriodo;
    private javax.swing.JMenuItem menProcesar;
    private javax.swing.JMenu menProcesarPagos;
    private javax.swing.JMenuItem menRegistraAfp;
    private javax.swing.JMenuItem menRegistraContrato;
    private javax.swing.JMenuItem menRegistraEmpleado;
    private javax.swing.JMenuItem menRegistraPeriodo;
    private javax.swing.JMenu menSesion;
    private javax.swing.JMenuItem menUltimaSesion;
    // End of variables declaration//GEN-END:variables
}
